# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cassandra-model}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tien Le"]
  s.date = %q{2010-10-21}
  s.description = %q{Cassandra-model allows you to map ColumnFamily/SuperColumnFamily in Cassandra to Ruby objects. It was designed to be fast and simple.}
  s.email = %q{tienlx@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/cassandra-model.rb",
     "lib/cassandra-model/base.rb",
     "lib/cassandra-model/callbacks.rb",
     "lib/cassandra-model/persistence.rb",
     "lib/cassandra-model/types.rb",
     "test/base_test.rb",
     "test/callbacks_test.rb",
     "test/cassandra_model_test.rb",
     "test/config/cassandra.in.sh",
     "test/config/log4j-tools.properties",
     "test/config/log4j.properties",
     "test/config/storage-conf.xml",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/infinity42/cassandra-model}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Minimal models for Cassandra.}
  s.test_files = [
    "test/base_test.rb",
     "test/test_helper.rb",
     "test/cassandra_model_test.rb",
     "test/callbacks_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<cassandra>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<cassandra>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<cassandra>, [">= 0"])
  end
end

